# permissions for end users to edit hcajobs.
apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRole
metadata:
  name: hcajob-editor-role
rules:
- apiGroups:
  - autoscale.njtech.edu.cn
  resources:
  - hcajobs
  verbs:
  - create
  - delete
  - get
  - list
  - patch
  - update
  - watch
- apiGroups:
  - autoscale.njtech.edu.cn
  resources:
  - hcajobs/status
  verbs:
  - get
