# permissions for end users to view hcajobs.
apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRole
metadata:
  name: hcajob-viewer-role
rules:
- apiGroups:
  - autoscale.njtech.edu.cn
  resources:
  - hcajobs
  verbs:
  - get
  - list
  - watch
- apiGroups:
  - autoscale.njtech.edu.cn
  resources:
  - hcajobs/status
  verbs:
  - get
